language: go
go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/0.10.2 && go install && cd -
  - glide install

